name: C++ CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install lcov (for coverage report)
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: Compile Code and Tests with Coverage flags
      run: |
        g++ -O0 --coverage test_main.cpp -o test_runner

    - name: Run Tests
      run: |
        ./test_runner

    - name: Generate Coverage Report
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info # убираем системные библиотеки
        genhtml coverage.info --output-directory out
        
    - name: Display Coverage in Logs
      run: |
        lcov --list coverage.info
