name: C++ CI Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install gcovr
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: Compile
      run: |
        g++ --coverage -O0 test_main.cpp -o test_runner

    - name: Run Tests
      run: |
        ./test_runner

    - name: Coverage Report
      run: |
        gcovr -r . --txt
